packages:
  - ./app
  - ./cdk
  - ./cdk/function

overrides:
  '@eslint/compat': ^2.0.0
  '@types/node': ^24.10.4
  '@vitest/ui': ^4.0.16
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  h3@<=1.15.4: '>=1.15.5'
  on-headers@<1.1.0: '>=1.1.0'
  seroval@<1.4.1: '>=1.4.1'
  vinxi: ^0.5.10
  vite: ^7.3.0
  vite-tsconfig-paths: ^6.0.3
  vitest: ^4.0.16
  eslint: '>=10'
  '@eslint/js': '>=10'
  '@stylistic/eslint-plugin': '>=5.0.0'
